import { query } from '../db/index.js';

export const ResumeModel = {
  /**
   * `id` is generated by the caller (uuid v4) so the S3 key can be built
   * before the row exists - the upload and the insert then reference the same id.
   */
  async create(
    { id, tenantId, userId, originalFilename, mimeType, sizeBytes, s3Key, contentHash },
    client = null
  ) {
    const run = client ? client.query.bind(client) : query;
    const { rows } = await run(
      `INSERT INTO resumes
         (id, tenant_id, user_id, original_filename, mime_type, size_bytes, s3_key, content_hash)
       VALUES (COALESCE($1, gen_random_uuid()), $2, $3, $4, $5, $6, $7, $8)
       RETURNING *`,
      [id ?? null, tenantId, userId, originalFilename, mimeType, sizeBytes, s3Key, contentHash]
    );
    return rows[0];
  },

  /** Always scoped by tenant - this is the multi-tenant guard rail. */
  async findById({ id, tenantId }) {
    const { rows } = await query('SELECT * FROM resumes WHERE id = $1 AND tenant_id = $2 LIMIT 1', [
      id,
      tenantId,
    ]);
    return rows[0] ?? null;
  },

  /**
   * Same bytes uploaded twice by the same user? Reuse the existing row and its
   * S3 object instead of paying for another PUT - and the worker will then hit
   * the Redis embedding cache too.
   */
  async findByContentHash({ tenantId, userId, contentHash }) {
    const { rows } = await query(
      `SELECT * FROM resumes
        WHERE tenant_id = $1 AND user_id = $2 AND content_hash = $3
        ORDER BY created_at DESC
        LIMIT 1`,
      [tenantId, userId, contentHash]
    );
    return rows[0] ?? null;
  },

  async listByUser({ tenantId, userId, limit = 20, offset = 0 }) {
    const { rows } = await query(
      `SELECT id, original_filename, mime_type, size_bytes, created_at
         FROM resumes
        WHERE tenant_id = $1 AND user_id = $2
        ORDER BY created_at DESC
        LIMIT $3 OFFSET $4`,
      [tenantId, userId, limit, offset]
    );
    return rows;
  },
};

export default ResumeModel;
